apiVersion: batch/v1
kind: Job
metadata:
  name: testexecutor
  namespace: test-runner
spec:
  manualSelector: true
  selector:
    matchLabels:
      app: testexecutor
  activeDeadlineSeconds: %%TIMEOUT%%  #Prevent jobs from continuing to spawn for eternity if failing.
  completions: %%COMPLETIONS%%    #Number of completions required for job to succeed
  parallelism: %%PARRALLELISM%%    #Number of pods that can run in parrallel to reach desired completions
  template:
    metadata:
      name: testexecutor
      labels:
        app: testexecutor
    spec:
      nodeSelector:
        role: minion
      volumes:
      - name: secret-volume
        secret:
          secretName: test-runner-secrets
      containers:
      - name: testexecutor
        image: pearsontechnology/test-executor-app:1.0.6
        volumeMounts:
        - mountPath: /etc/secret-volume
          name: secret-volume
          readOnly: true
        env:
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: test-runner-secrets
              key: git-username
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-runner-secrets
              key: git-password
        - name: STACK_ID
          value: "%%STACK_ID%%"
        - name: ANSIBLE_BRANCH
          value: "%%ANSIBLE_BRANCH%%"
        - name: REGION
          value: "%%REGION%%"
        - name: ENVIRONMENT
          value: "%%ENVIRONMENT%%"
        - name: BRAIN
          value: "%%BRAIN%%"
        - name: GIT_REPO
          value: "git@github.com:pearsontechnology/kubernetes-tests.git"
        - name: GIT_BRANCH
          value: "%%GIT_BRANCH%%"
        - name: KUBE_PASS
          value: "%%KUBE_PASS%%"
        - name: ST2_PASSWORD
          value: "%%ST2_PASSWORD%%"
        - name: KUBERNETES_VERSION
          value: "%%KUBERNETES_VERSION%%"
        - name: MINION_COUNT
          value: "%%MINION_COUNT%%"
        - name: DEBUG
          value: "%%DEBUG%%"
        - name: CONSUL_MASTER_TOKEN
          value: "%%CONSUL_MASTER_TOKEN%%"
        - name: DOMAIN
          value: "%%DOMAIN%%"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      restartPolicy: Never
      nodeSelector:
        role: minion
